services:
  Phpro\SuluMessengerFailedQueueBundle\Domain\Command\DeleteHandler:
    arguments:
      - '@sulu_messenger_failed_queue.transport'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Command\DeleteHandlerInterface: '@Phpro\SuluMessengerFailedQueueBundle\Domain\Command\DeleteHandler'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RetryHandler:
    arguments:
      - 'failed'
      - '@sulu_messenger_failed_queue.transport'
      - '@messenger.routable_message_bus'
      - '@event_dispatcher'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RetryHandlerInterface: '@Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RetryHandler'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RequeueHandler:
    arguments:
      $receiver: '@sulu_messenger_failed_queue.transport'
      $messageBus: '@messenger.routable_message_bus'
      $stampsToRemove:
        - 'Symfony\Component\Messenger\Stamp\ErrorDetailsStamp'
        - 'Symfony\Component\Messenger\Stamp\DelayStamp'
        - 'Symfony\Component\Messenger\Stamp\RedeliveryStamp'
        - 'Symfony\Component\Messenger\Stamp\SentToFailureTransportStamp'
        - 'Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineReceivedStamp'
        - 'Symfony\Component\Messenger\Stamp\TransportMessageIdStamp'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RequeueHandlerInterface: '@Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RequeueHandler'
