services:
  Phpro\SuluMessengerFailedQueueBundle\Presentation\Controller\Admin\DeleteController:
    arguments:
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Command\DeleteHandlerInterface'
    tags: ['controller.service_arguments']

  Phpro\SuluMessengerFailedQueueBundle\Presentation\Controller\Admin\FetchController:
    arguments:
      - '@serializer'
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessageInterface'
    tags: [ 'controller.service_arguments' ]

  Phpro\SuluMessengerFailedQueueBundle\Presentation\Controller\Admin\ListController:
    arguments:
      - '@serializer'
      - '@sulu_core.list_rest_helper'
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessagesInterface'
    tags: ['controller.service_arguments']

  Phpro\SuluMessengerFailedQueueBundle\Presentation\Controller\Admin\RequeueController:
    arguments:
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RequeueHandlerInterface'
    tags: [ 'controller.service_arguments' ]

  Phpro\SuluMessengerFailedQueueBundle\Presentation\Controller\Admin\RetryController:
    arguments:
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Command\RetryHandlerInterface'
    tags: [ 'controller.service_arguments' ]