services:
  Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessage:
    arguments:
      - '@sulu_messenger_failed_queue.transport'
      - '@serializer'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessageInterface: '@Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessage'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessages:
    arguments:
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Repository\FailedQueueRepository'
      - '@Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessageInterface'

  Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessagesInterface: '@Phpro\SuluMessengerFailedQueueBundle\Domain\Query\FetchMessages'
