services:
  Phpro\SuluMessengerFailedQueueBundle\Infrastructure\Doctrine\Repository\DoctrineFailedQueueRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%sulu_messenger_failed_queue.table%'
      - '%sulu_messenger_failed_queue.queue_name%'
  Phpro\SuluMessengerFailedQueueBundle\Domain\Repository\FailedQueueRepository: '@Phpro\SuluMessengerFailedQueueBundle\Infrastructure\Doctrine\Repository\DoctrineFailedQueueRepository'
